// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3AtTa9VTz4sA5qk-KYybUBUJql6svZc',
    appId: '1:79556948974:web:446b024c412f7c061094ff',
    messagingSenderId: '79556948974',
    projectId: 'todo2023n2116',
    authDomain: 'todo2023n2116.firebaseapp.com',
    storageBucket: 'todo2023n2116.firebasestorage.app',
    measurementId: 'G-00ZG2NPZB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-vrxOaVTmFhTV3TJUu_X5_73_iursmks',
    appId: '1:79556948974:android:0ac4e3018de861301094ff',
    messagingSenderId: '79556948974',
    projectId: 'todo2023n2116',
    storageBucket: 'todo2023n2116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJfEIvsHwfWbfcKTuRbklMgoS-eeNDPGI',
    appId: '1:79556948974:ios:549831350d214f251094ff',
    messagingSenderId: '79556948974',
    projectId: 'todo2023n2116',
    storageBucket: 'todo2023n2116.firebasestorage.app',
    iosClientId: '79556948974-1dg2r1lspt1mmuarltofrqbdso430lt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJfEIvsHwfWbfcKTuRbklMgoS-eeNDPGI',
    appId: '1:79556948974:ios:549831350d214f251094ff',
    messagingSenderId: '79556948974',
    projectId: 'todo2023n2116',
    storageBucket: 'todo2023n2116.firebasestorage.app',
    iosClientId: '79556948974-1dg2r1lspt1mmuarltofrqbdso430lt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg3AtTa9VTz4sA5qk-KYybUBUJql6svZc',
    appId: '1:79556948974:web:88d8890ff4f3773a1094ff',
    messagingSenderId: '79556948974',
    projectId: 'todo2023n2116',
    authDomain: 'todo2023n2116.firebaseapp.com',
    storageBucket: 'todo2023n2116.firebasestorage.app',
    measurementId: 'G-J80DYYVSG9',
  );
}
